apiVersion: v1
kind: Secret
metadata:
  name: credentials-azure
  namespace: velero
data:
  cloud: >-
    QVpVUkVfU1RPUkFHRV9BQ0NPVU5UX0FDQ0VTU19LRVk9WjhHSnl6RDM2QzVCU0tPTXFkNk40Tlg3N1YyS0VlNEU0VFE3SHAzbXZ2dXNBRmQrbXpYU0lTUi9RUUhYNWZ2RkRCYkZmUUNOaGtJMytBU3RrVi9HOHc9PQpBWlVSRV9DTE9VRF9OQU1FPUF6dXJlUHVibGljQ2xvdWQK
type: Opaque